### ISSUE TITLE
[dwarf:] DW_AT_declaration is NOT supported

### ISSUE THREAD

**Issue by qwertyuiopxu1** [DanielT/a2ltool#38]
Hi, when i  use a2ltool to update a2l address, there are some error info about struct byte size attribute[ see pic1]. then i try to debug the root casue, in the elf file, the DW_TAG_structure_type has the DW_AT_declaration field, but not the size field[ see pic2]. and in the elf file the type definition is defined in another location[ see pic3]. so how to solve this problem?
 
![image](https://github.com/user-attachments/assets/f09d89c4-8643-442f-804b-462c82886754)
![image](https://github.com/user-attachments/assets/e06f28f7-1f6d-43f1-93c9-7904db23135e)
![image](https://github.com/user-attachments/assets/fc923b22-23b9-4f82-a57c-7e81b14561c6)

**Comment by DanielT** [comment]
Hi,
Thanks for the bug report.
Can you also post the text or image of the type definition of Dma_TransactionCtrlSetType?
Your pic3 only shows the typedef for the structure, which is not helpful. The relevant info seems to be right under the part in pic3.

**Comment by DanielT** [comment]
Can you test the branch I just pushed?
Without additional info I was guessing what to do exactly, so it would be good if you could confirm if this works

**Comment by qwertyuiopxu1** [comment]
Hi,
for somecases, it works, but some are still not work correctly.

**Comment by huibing** [comment]
hi, @DanielT 
I find out why this new branch works for some cases(new code resolve this error), while does not work for some other cases:
the pic below shows some of the original errors during parsing elf types:
the red block indicates the error where type reading encounter error because its corresponding entry does not contain byte size info;
As you can see, in the cases where the upper type is a DW_TAG_pointer_type（✔️）, this error will not occur using new code;  however, in the cases where the upper type is not DW_TAG_pointer_type（✖️）, this error persists.
I think this could be the case when pointer points to a const type.
![Snipaste_2024-09-25_11-15-11](https://github.com/user-attachments/assets/9b1006d1-70e7-4cf0-a885-73f385ff1aad)

BTW, in the elf file, these types entries which cause the errors all have the identical structure with DW_AT_declaration set:
![image](https://github.com/user-attachments/assets/e580e50b-92b7-4e30-addc-f469c136026e)
![image](https://github.com/user-attachments/assets/50b2ce99-b3b2-4825-8309-07926cb24dea)
![image](https://github.com/user-attachments/assets/f917d789-0d79-4a49-8169-e9f22c5e2c6d)
![image](https://github.com/user-attachments/assets/329437ec-eb75-492d-9173-28be985a67cf)

**Comment by DanielT** [comment]
That's excellent information. I can see why my first try only works in some cases.
I should be able to use this info to fix the problem.

I would also like to try to test this myself. Do you know what compiler was used to create the elf file you're working with?

**Comment by huibing** [comment]
> That's excellent information. I can see why my first try only works in some cases. I should be able to use this info to fix the problem.
> 
> I would also like to try to test this myself. Do you know what compiler was used to create the elf file you're working with?

hightec compiler tricore-gcc with -O2

**Comment by DanielT** [comment]
I just pushed the branch "incomplete_types_v2", which should fully fix your problem.
Please test!

**Comment by huibing** [comment]
> I just pushed the branch "incomplete_types_v2", which should fully fix your problem. Please test!

Yes, this time all related errors are eliminated.
Thanks for the effort.
